dist: xenial
language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: "mvn clean install -Dmaven.test.skip=true "
script:
  - cd binaries
  - tar -xvf bindaas*
  - cd bin
  - ./startup.sh
  - sleep 15s
  - echo "running tests"
  - mvn test
  - ./shutdown.sh